### ISSUE TITLE
autoFocusInput on textarea

### ISSUE THREAD

**Issue by versteey** [Kinark/Materialize-stepper#14] opened 2017-06-15 13:53 UTC
$.fn.openStep = function(step, callback) {
   settings = $(this).closest('ul.stepper').data('settings');
   $this = this;
   step_num = step - 1;
   step = this.find('.step:visible:eq('+step_num+')');
   if(step.hasClass('active')) return;
   active = this.find('.step.active');
   prev_active = next = $(this.children('.step:visible')).index($(active));
   order = step_num > prev_active ? 1 : 0;
   if(active.hasClass('feedbacking')) $this.destroyFeedback();
   active.closeAction(order);
   step.openAction(order, function(){
      if(settings.autoFocusInput) step.find('input:enabled:visible:first').focus();
      $this.trigger('stepchange').trigger('step'+(step_num+1));
      if(step.data('event')) $this.trigger(step.data('event'));
      if(callback)callback();
   });
};

this function will not work on textarea's, note the selector 'input:enabled:visible:first' should be  ':input:enabled:visible:first'. Note the colon symbol.

**Comment by bastianwegge** [comment] 2017-06-15 15:50
Hey @versteey, thank you for the hint! Is this somewhere in the code? Since there is no reference and hardly any context it's hard to understand your comment. Would you mind editing your comment with a bit of markup and maybe reproduce the error you are mentioning somewhere? Like codepen.io or jsfiddle?

**Comment by versteey** [comment] 2017-06-16 08:44
The function openStep reacts on the setting autoFocusInput, this is not working for textarea's or select. 
This is because the selector for setting the foxus only works on <input>.

i think the selector 'input:enabled:visible:first' should be changed to ':input:enabled:visible:first'

See: https://stackoverflow.com/questions/4328381/jquery-set-focus-on-the-first-enabled-input-or-select-or-textarea-on-the-page

Or copy the content of my little example into w3schools 
https://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_hide 
[input selector.txt](https://github.com/Kinark/Materialize-stepper/files/1080218/input.selector.txt)

**Comment by Kinark** [comment] 2019-03-09 23:20
Everything is fixed by now, I guess. I'm closing this issue.

**Closed by Kinark** 2019-03-09 23:20 UTC
